---
###This is a local template only needed when invoking the function using samlocal - https://github.com/awslabs/aws-sam-cli
###Please note that the template resource name, function file name and handler must all match for each function to run in sam local
AWSTemplateFormatVersion : '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Template to create a public S3 bucket solution

Resources:

  creates3:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: creates3.handler
      Timeout: 10
      Environment:
        Variables:
          attributeName: bucketname
          tableName: Public-S3-Buckets

  createdynamo:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: createdynamo.handler
      Timeout: 10
      Environment:
        Variables:
          attributeName: bucketname
          tableName: Public-S3-Buckets

  putdynamo:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: putdynamo.handler
      Timeout: 10
      Environment:
        Variables:
          item: bucketname
          tableName: Public-S3-Buckets
          buckets: zzzzstevetest1 zzzzstevetest123
